manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: cay
      url-base: https://github.com/caksoylar
    - name: pete
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: pete
      revision: power/domains-and-device-runtime
      import: app/west.yml
  self:
    path: config
