manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk
      url-base: https://github.com/krikun98
  projects:   
    - name: forkzmk
      remote: zmk
      revision: mouse-pr
  self:
    path: config
